### ISSUE TITLE
About Antenna

### ISSUE THREAD

**Issue by junglej** [ucsdwcsng/wiros_processing_node#4]
I saw your configuration about the antenna in Antennna.md file. I have a question about that. I used ASUS RT-AC86u to collect CSI data. The detail about the placement of antennas is that?
![Untitled](https://github.com/ucsdwcsng/wiros_processing_node/assets/54071634/3331cb78-d884-43ec-b77b-be222eaa4e82)

And you place the antenna at X-Axis like this: (This X-Axis is global? or Robot's?)
```
3 
1
2
0 --X-Axis-->
```
and set the RX position parameter is 
```
<rosparam param="rx_position"> [0,  0,
    0,  0.052,
    0,  0.026,
    0,  0.078] </rosparam>
```
So I want to check the correspondence between the antenna and the parameters.
```
3  -- COM4
1  -- COM8
2  -- COM35
0  -- COM6          --X-Axis-->
```
Many thanks!
Looking forward to your reply!

**Comment by a-arun1** [comment]
Hello @junglej 

Please consider the following image (antennas ordered with 1-indexing):

![ap-fig](https://github.com/ucsdwcsng/wiros_processing_node/assets/25189334/489fae70-b1cf-4a98-b6e6-eb39edb49e62)

According to this, the coordinate system is in local-coordinate to the access point. And the antennas.md file needs the following corrections (antennas ordered with 0-indexing): 

```
0  --X-Axis--> 
2
1
3 
```
and antenna locations as: 

```
<rosparam param="rx_position"> [0,  0,
    0, -0.052,
    0,  -0.026,
    0,  -0.078] </rosparam>

```

We apologize for the confusion and thank you for spotting the error in the docs!

**Comment by junglej** [comment]
Thanks for your help!!!
