### ISSUE TITLE
Bill of material for static compensation

### ISSUE THREAD

**Issue by patorrad** [ucsdwcsng/wiros_processing_node#5]
Do you have a recommendation for the attenuator (make and model)? Is there only one required or multiple in series? I was confused because it says "Connect the attenuators to the input of the splitter".

Thanks!

**Comment by wshunter** [comment]
The setup we have used is : Transmitter <—> attenuators <—> 1 to 4 splitter <—> 4 SMA ports on the ASUS. I will send a photo of the setup as well as the part numbers later this weekend. However I think any RF splitter rated for 5GHz should work.
