### ISSUE TITLE
Error when running spotfi algo

### ISSUE THREAD

**Issue by patorrad** [ucsdwcsng/wiros_processing_node#8]
Get the following error:

`[ERROR] [1719089235.451806]: Error in computing AoA and profile
[ERROR] [1719089235.453965]: name 'rx_pos' is not defined
Traceback (most recent call last):
  File "/home/mushrorinrf/wifi_ws/src/wiros_processing_node/src/csi_utils/aoa_node_main.py", line 189, in csi_callback
    self.last_aoa, prof = self.aoa_sensors[mac](self.last_channel, (msg.chan, bw))
  File "/home/mushrorinrf/wifi_ws/src/wiros_processing_node/src/csi_utils/transform_utils.py", line 432, in __call__
    self.steering_mat[chanspec] = spotfi_mat(rx_pos, freqs,
NameError: name 'rx_pos' is not defined
`

This is solved by modifying the call to method spotfi_mat() in line 431 in transform_utils.py. Attribute rx_pos should be self.rx_pos.

**Comment by wshunter** [comment]
Thanks for testing this, please make a PR with all of the issues you find and I’ll review and update everything. Also note that the current SpotFi code with only work with a uniform linear array, this is a limitation of the SpotFi algorithm.
